name: S3 Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-to-s3-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Rebuild node-sass if needed
        run: npm rebuild node-sass

      - name: Update Packages
        run: npx browserslist@latest --update-db

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_REGION: 'eu-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            ./dist s3://juicyllamavuedemo
